spring:
  application:
    name: "network-controller"

  profiles:
    active: default

  data:
    mongodb:
      host: localhost
      port: 27017
      database: network-controller_db
      username: admin
      password: supersecret
      authentication-database: admin

  #TODO: keep?
  threads:
    virtual:
      enabled: true

  graphql:
    graphiql:
      enabled: true

logging:
  level:
    com.alesmontaldo.network_controller: DEBUG
    org.springframework.graphql: DEBUG
    org.springframework.graphql.data.method.annotation.support.AnnotatedControllerConfigurer: TRACE

---
spring:
  profiles:
#    active: in-memory
    active: mongo

# TODO remove here
#spring:
#  config:
#    activate:
#      on-profile: in-memory
  # No MongoDB configuration needed for in-memory profile
