spring:
  application:
    name: "network-controller"

  profiles:
    active: in-memory

  data:
    mongodb:
      host: localhost
      port: 27017
      database: network-controller_db
      username: admin
      password: supersecret
      authentication-database: admin

  graphql:
    graphiql:
      enabled: true
