name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # MongoDB service container
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: supersecret
          MONGO_INITDB_DATABASE: network-controller_db
        # Set health checks to wait until mongodb is ready
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ping:1})' --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Test with Gradle
      run: ./gradlew test
      env:
        # Pass MongoDB connection details to tests
        SPRING_DATA_MONGODB_HOST: localhost
        SPRING_DATA_MONGODB_PORT: 27017
        SPRING_DATA_MONGODB_DATABASE: network-controller_db
        SPRING_DATA_MONGODB_USERNAME: admin
        SPRING_DATA_MONGODB_PASSWORD: supersecret
        SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
